services:
  api:
    build: ./server
    container_name: clouddesk-api
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URI: mongodb://mongo:27017/clouddesk
      JWT_SECRET: local_docker_dev_secret_change_later
      NODE_ENV: development
      CLIENT_URL: http://localhost:5173
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: clouddesk-mongo
    ports:
      - "27017:27017"
    volumes:
      - clouddesk-mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: clouddesk-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  clouddesk-mongo-data:
